# Deploy Firebase Functions on merge to main branch
name: Deploy Firebase Functions on merge
on:
  push:
    branches:
      - main
jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies in functions directory
        run: cd functions && npm ci

      - name: Create .env file
        run: |
          cd functions
          echo "DB_PROVIDER=mongodb" > .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          echo "STORAGE_PROVIDER=firebase" >> .env
          echo "STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> .env

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Functions
        run: firebase deploy --project biz-tracker-a5562 --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BIZ_TRACKER_A5562 }}